/* 해모아 로컬 프로토타입: API 교체 지점은 analyseImage()에 분리했습니다. */
const app = document.querySelector('#app');
const imageInput = document.querySelector('#imageInput');
let cameraStream = null;

const LOCATIONS = {
  '광안리': [35.1532, 129.1187], '해운대': [35.1587, 129.1604], '송정': [35.1793, 129.1995],
  '다대포': [35.0488, 128.9651], '영도': [35.0784, 129.0708], '오륙도': [35.0998, 129.1220], '기장': [35.2446, 129.2130]
};
const FISH = [
  { name:'감성돔', category:'어류', classification:'도미과', features:'암초와 방파제 주변에 서식하는 연안 어종입니다.', habitat:'연안 암초·방파제', danger:'주의', edible:'가능', notice:'등지느러미 가시에 찔리지 않도록 주의하세요.', emoji:'🐟' },
  { name:'볼락', category:'어류', classification:'양볼락과', features:'항구와 테트라포드 주변에서 잘 발견되는 야행성 어종입니다.', habitat:'항구·암초 지대', danger:'안전', edible:'가능', notice:'작은 개체는 방류를 권장합니다.', emoji:'🐠' },
  { name:'농어', category:'어류', classification:'농어과', features:'은빛 몸과 강한 입질이 특징인 회유성 어종입니다.', habitat:'하구·연안', danger:'안전', edible:'가능', notice:'지느러미 끝을 조심하세요.', emoji:'🐟' },
  { name:'쥐치', category:'어류', classification:'쥐치과', features:'납작한 몸과 단단한 이빨이 특징입니다.', habitat:'암초·해조류 지대', danger:'안전', edible:'가능', notice:'입 주변을 만질 때 주의하세요.', emoji:'🐡' },
  { name:'복어', category:'어류', classification:'참복과', features:'위협을 받으면 몸을 부풀리는 독성 어종입니다.', habitat:'연안 모래·암초', danger:'위험', edible:'불가', notice:'절대 섭취하거나 맨손으로 다루지 마세요.', emoji:'🐡' },
  { name:'문어', category:'연체동물', classification:'문어과', features:'여덟 개의 팔과 뛰어난 위장 능력을 가졌습니다.', habitat:'바위틈·해저', danger:'주의', edible:'가능', notice:'흡반에 손가락이 끼지 않게 주의하세요.', emoji:'🐙' },
  { name:'꽃게', category:'갑각류', classification:'꽃게과', features:'푸른빛 다리와 넓적한 등딱지가 특징입니다.', habitat:'모래·갯벌', danger:'주의', edible:'가능', notice:'집게에 물리지 않도록 뒤쪽을 잡으세요.', emoji:'🦀' }
];
const COMMUNITY = [
  { location:'광안리', latitude:35.1532, longitude:129.1187, name:'감성돔', category:'어류', length:51.2, userName:'부산 바다낚시' },
  { location:'민락수변공원', latitude:35.1556, longitude:129.1246, name:'농어', category:'어류', length:null, userName:'민락 낚시러' },
  { location:'송정', latitude:35.1801, longitude:129.1998, name:'볼락', category:'어류', length:38.4, userName:'송정 피싱' },
  { location:'영도 태종대', latitude:35.0511, longitude:129.0873, name:'문어', category:'연체동물', length:null, userName:'영도 낚시꾼' },
  { location:'오륙도', latitude:35.0998, longitude:129.1220, name:'쥐치', category:'어류', length:29.6, userName:'오륙도 낚시회' },
  { location:'해운대', latitude:35.1587, longitude:129.1604, name:'꽃게', category:'갑각류', length:null, userName:'해운대 낚시회' },
  { location:'다대포', latitude:35.0488, longitude:128.9651, name:'감성돔', category:'어류', length:42.1, userName:'다대포 바다팀' }
];
let state = { screen:'camera', lengthOn:false, capture:null, fish:null, confidence:0, filter:'전체', mapMode:'mine', selected:null, pendingLength:null, rankTab:'top' };
const points=()=>Number(localStorage.getItem('haemoa-points')||0);
function grantPoints(amount, message){localStorage.setItem('haemoa-points',points()+amount);app.insertAdjacentHTML('beforeend',`<div class="reward-modal"><div><span>🎉</span><h2>+${amount}P</h2><p>${message}</p><button class="primary" onclick="this.closest('.reward-modal').remove()">확인</button></div></div>`)}
const BUSAN_CENTER = [35.1796, 129.0756];
let leafletMap = null, pendingLocation = null;
const records = () => JSON.parse(localStorage.getItem('haemoa-records') || '[]');
const saveRecords = value => localStorage.setItem('haemoa-records', JSON.stringify(value));

function stopCamera() { if (cameraStream) { cameraStream.getTracks().forEach(track => track.stop()); cameraStream = null; } }
function go(screen) { stopCamera(); state.screen = screen; state.selected = null; if (screen === 'camera') state.capture = null; render(); if (screen === 'camera') startCamera(); }
function render() { app.innerHTML = ({camera, analysis, form, records:recordList, map, ranking, shop, locationConfirm}[state.screen] || camera)(); if (state.screen === 'analysis') setTimeout(showAnalysis, 650); if(state.screen==='map') setTimeout(initRealMap,0); }
function backButton() { return '<button class="back-fab" onclick="go(\'camera\')" aria-label="카메라로 돌아가기">⌾</button>'; }

function camera() { return `<div class="screen camera-screen"><div class="viewfinder"><video id="video" autoplay playsinline muted></video><div class="guide"></div></div><header class="topbar"><div class="brand-logo"><span class="logo-wave">≈</span><span>해모아</span><small>BUSAN SEA</small></div><div class="top-actions"><button class="point-pill" onclick="go('shop')">P ${points()}</button><button class="rank-launch" onclick="go('ranking')">♕ <span>랭킹</span></button></div></header><div class="camera-actions"><button class="tiny-nav" onclick="go('records')" aria-label="나의 기록">▤</button><button class="shutter" onclick="capturePhoto()" aria-label="사진 촬영"></button><button class="tiny-nav map-nav" onclick="go('map')" aria-label="바다 생물 지도">🗺</button></div></div>`; }
async function startCamera() { try { cameraStream = await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}, audio:false}); const video = document.querySelector('#video'); if (video) video.srcObject = cameraStream; } catch { toast('카메라 권한이 없으면 촬영 버튼으로 사진을 선택할 수 있어요.'); } }
function capturePhoto() { const video = document.querySelector('#video'); if (video && video.videoWidth) { const limit=1200, ratio=Math.min(1,limit/video.videoWidth); const canvas = document.createElement('canvas'); canvas.width=Math.round(video.videoWidth*ratio); canvas.height=Math.round(video.videoHeight*ratio); canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height); state.capture=canvas.toDataURL('image/jpeg',.72); stopCamera(); beginAnalysis(); } else imageInput.click(); }
imageInput.addEventListener('change', e => { const file=e.target.files[0]; if (!file) return; const reader=new FileReader(); reader.onload=()=>{const image=new Image();image.onload=()=>{const max=1200,ratio=Math.min(1,max/image.width),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*ratio);canvas.height=Math.round(image.height*ratio);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);state.capture=canvas.toDataURL('image/jpeg',.72);beginAnalysis()};image.src=reader.result}; reader.readAsDataURL(file); e.target.value=''; });
function beginAnalysis() { state.fish=null; state.confidence=0; go('analysis'); }

/* 실제 Vision API 연결 시 이 함수만 async API 호출로 교체하면 됩니다.
   현재는 업로드한 이미지의 픽셀 특징을 해시해, 같은 사진에는 항상 같은 결과를 제공합니다. */
async function analyseImage(dataUrl) { return new Promise(resolve => { const image=new Image(); image.onload=()=>{ const canvas=document.createElement('canvas'); canvas.width=24; canvas.height=24; const ctx=canvas.getContext('2d'); ctx.drawImage(image,0,0,24,24); const d=ctx.getImageData(0,0,24,24).data; let signature=0; for(let i=0;i<d.length;i+=16) signature=(signature*31+d[i]*3+d[i+1]*5+d[i+2]*7)>>>0; resolve({ fish:FISH[signature%FISH.length], confidence:78+(signature%18) }); }; image.src=dataUrl; }); }
function analysis() { const fish=state.fish || FISH[0]; return `<div class="screen"><button class="icon-btn dark-icon" onclick="go('camera')">‹</button><h1 class="page-title">사진 분석</h1><p class="sub">사진의 시각적 특징을 분석하고 있어요.</p><div class="analysis-card"><div class="photo-preview">${state.capture?`<img src="${state.capture}" alt="촬영한 해양 생물">`:''}<div id="analyzing" class="analyzing"><div><div class="scan"></div><p>AI가 해양 생물을 분석하고 있습니다...</p></div></div></div><div id="analysisInfo" class="hidden"><p class="ai-result">AI 판별 신뢰도 <b>${state.confidence}%</b></p>${fishInfo(fish)}<button class="primary" onclick="go('form')">이 생물 기록으로 저장</button></div></div></div>`; }
async function showAnalysis() { const mask=document.querySelector('#analyzing'), info=document.querySelector('#analysisInfo'); if (!mask || !info) return; const result=await analyseImage(state.capture); state.fish=result.fish; state.confidence=result.confidence; mask.classList.add('hidden'); info.innerHTML=`<p class="ai-result">AI 판별 신뢰도 <b>${state.confidence}%</b></p>${fishInfo(state.fish)}<button class="primary" onclick="go('form')">이 생물 기록으로 저장</button>`; info.classList.remove('hidden'); }
function fishInfo(f) { return `<div class="fish-head"><div class="fish-icon">${f.emoji}</div><div><h2>${f.name}</h2><p>${f.classification} · ${f.category}</p></div><span class="danger ${dangerClass(f.danger)}">${f.danger}</span></div><dl class="info-grid"><dt>특징</dt><dd>${f.features}</dd><dt>서식 환경</dt><dd>${f.habitat}</dd><dt>식용 가능</dt><dd>${f.edible}</dd><dt>주의사항</dt><dd>${f.notice}</dd></dl>`; }
function dangerClass(value) { return value==='안전'?'safe':value==='주의'?'caution':'risky'; }

function form() { return `<div class="screen"><button class="icon-btn dark-icon" onclick="go('analysis')">‹</button><h1 class="page-title">발견 기록</h1><p class="sub">길이 입력은 선택사항입니다.</p><div class="analysis-card">${fishInfo(state.fish)}<div class="toggle-box"><b>길이 기록</b><button onclick="toggleLength()" class="switch ${state.lengthOn?'on':''}" aria-label="길이 기록 켜기 또는 끄기"><i></i></button></div>${state.lengthOn?'<div class="field"><label>길이를 입력해주세요</label><input id="length" type="number" step="0.1" inputmode="decimal" placeholder="예: 34.5"><small>cm 단위 · 소수점 입력 가능</small></div>':''}<div id="gpsStatus" class="gps-status">기록 저장 전 실제 GPS 위치를 확인합니다.</div><button class="primary" onclick="requestGpsForRecord()">현재 위치 확인하기</button></div>${backButton()}</div>`; }
function toggleLength() { state.lengthOn=!state.lengthOn; render(); }
function requestGpsForRecord() { state.pendingLength=state.lengthOn?Number.parseFloat(document.querySelector('#length')?.value):null; const status=document.querySelector('#gpsStatus'); status.textContent='현재 위치를 확인하고 있습니다...'; if(!navigator.geolocation){ status.textContent='이 브라우저에서는 위치 정보를 사용할 수 없습니다.'; return; } navigator.geolocation.getCurrentPosition(position=>{ pendingLocation={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy}; confirmLocation(); },()=>{ status.textContent='위치 확인에 실패했습니다. localhost 또는 HTTPS에서 위치 권한을 허용해주세요.'; },{enableHighAccuracy:true,timeout:10000,maximumAge:0}); }
function confirmLocation() { state.screen='locationConfirm'; render(); setTimeout(initLocationMap,0); }
function locationConfirm() { return `<div class="screen"><h1 class="page-title">발견 위치 확인</h1><p class="sub">현재 위치가 정확하지 않다면 마커를 움직여 실제 발견 위치를 지정해주세요.</p><div class="gps-status">위치 확인 완료 · 정확도 ±${Math.round(pendingLocation.accuracy)}m</div><div id="locationMap" class="location-map"></div><button class="primary" onclick="storeRecord()">이 위치로 기록 저장</button></div>`; }
function initLocationMap() { const map=L.map('locationMap').setView([pendingLocation.latitude,pendingLocation.longitude],16); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map); const marker=L.marker([pendingLocation.latitude,pendingLocation.longitude],{draggable:true}).addTo(map); marker.on('dragend',()=>{const p=marker.getLatLng();pendingLocation.latitude=p.lat;pendingLocation.longitude=p.lng;}); }
function saveGpsRecord() { if(!pendingLocation || !Number.isFinite(pendingLocation.latitude) || !Number.isFinite(pendingLocation.longitude)){ toast('위치 정보가 없어 저장할 수 없습니다. 위치를 다시 확인해주세요.'); return false; } if(!state.fish){toast('생물 분석 결과가 없어 저장할 수 없습니다.');return false;} const raw=state.pendingLength, now=new Date(); const r={id:Date.now(),userId:'me',userName:'나',...state.fish,length:Number.isFinite(raw)?raw:null,location:pendingLocation.address||`${pendingLocation.latitude.toFixed(6)}, ${pendingLocation.longitude.toFixed(6)}`,latitude:pendingLocation.latitude,longitude:pendingLocation.longitude,accuracy:pendingLocation.accuracy,date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),image:state.capture}; try{saveRecords([r,...records()]);return true;}catch(error){toast('저장 공간이 부족합니다. 브라우저 사이트 데이터를 정리한 뒤 다시 시도해주세요.');console.error('해모아 기록 저장 실패:',error);return false;} }

function filters() { return `<div class="filters">${['전체','어류','갑각류','연체동물','기타'].map(x=>`<button class="filter ${state.filter===x?'active':''}" onclick="setFilter('${x}')">${x}</button>`).join('')}</div>`; }
function setFilter(filter) { state.filter=filter; render(); }
function applyFilter(list) { return state.filter==='전체'?list:list.filter(x=>x.category===state.filter); }
function recordCard(r) { return `<button class="record-card" onclick="detail(${r.id})"><div class="thumb">${r.image?`<img src="${r.image}" alt="${r.name}">`:r.emoji}</div><div class="record-meta"><h3>${r.name} ${r.length!=null?`<span class="tag">${r.length}cm</span>`:''}</h3><p>${r.date.replaceAll('-','.')} · ${r.time}</p><p>⌖ ${r.location}${r.length==null?' · 길이 미기록':''}</p></div><span>›</span></button>`; }
function recordList() { const list=applyFilter(records()); return `<div class="screen"><h1 class="page-title">나의 기록</h1><p class="sub">발견한 순간을 시간순으로 모아보세요.</p>${filters()}<div class="record-list">${list.length?list.map(recordCard).join(''):'<div class="empty">아직 저장한 기록이 없어요.<br>카메라로 첫 발견을 남겨보세요.</div>'}</div>${backButton()}</div>`; }
function detail(id) { const r=records().find(x=>x.id===id); if(!r)return; app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet"><button class="close" onclick="this.closest('.modal').remove()">×</button><div class="photo-preview">${r.image?`<img src="${r.image}" alt="${r.name}">`:''}</div>${fishInfo(r)}<dl class="info-grid"><dt>발견 일시</dt><dd>${r.date} ${r.time}</dd><dt>발견 위치</dt><dd>${r.location}</dd><dt>길이</dt><dd>${r.length!=null?r.length+' cm':'길이 미기록'}</dd></dl></div></div>`); }

function map() { const isMine=state.mapMode==='mine'; return `<div class="screen map-screen"><h1 class="page-title">바다 생물 지도</h1><div class="tabs"><button class="${isMine?'active':''}" onclick="setMapMode('mine')">나의 지도</button><button class="${!isMine?'active':''}" onclick="setMapMode('all')">모두의 지도</button></div>${filters()}<div id="leafletMap" class="leaflet-map" aria-label="실제 부산 지도"></div><div id="mapCard"></div>${backButton()}</div>`; }
function setMapMode(mode) { state.mapMode=mode; state.selected=null; render(); setTimeout(initRealMap,0); }
function initRealMap() { const el=document.querySelector('#leafletMap'); if(!el||!window.L)return; if(leafletMap)leafletMap.remove(); leafletMap=L.map(el).setView(BUSAN_CENTER,11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(leafletMap); const source=state.mapMode==='mine'?records().filter(r=>Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)):COMMUNITY; const list=applyFilter(source); const group=state.mapMode==='all'&&L.markerClusterGroup?L.markerClusterGroup():L.layerGroup(); list.forEach(record=>{const marker=L.marker([record.latitude,record.longitude],{icon:L.divIcon({className:'record-pin',iconSize:[14,14]})}); marker.on('click',()=>showMapCard(record)); group.addLayer(marker);}); group.addTo(leafletMap); if(list.length)leafletMap.fitBounds(group.getBounds(),{padding:[25,25],maxZoom:14}); }
function showMapCard(r) { const card=document.querySelector('#mapCard'); card.innerHTML=`<div class="map-card">${r.image?`<img src="${r.image}" alt="${r.name}">`:''}<b>${r.name}</b>${r.length!=null?' · '+r.length+'cm':''}<br><small>${r.date||'샘플 기록'} ${r.time||''}<br>${r.location}</small></div>`; }

function ranking() { const list=[...records().filter(x=>x.length!=null),...COMMUNITY.filter(x=>x.length!=null).map((x,i)=>({...x,id:'community'+i,userId:'other'}))].sort((a,b)=>b.length-a.length); return `<div class="screen"><h1 class="page-title">오늘의 순위</h1><p class="sub">길이를 직접 입력한 기록만 순위에 참여합니다.</p><div class="rank-top"><h2>🏆 이번 주 TOP 3</h2>${list.slice(0,3).map((r,i)=>`<div class="rank"><b class="rank-num">${i+1}</b><div><b>${r.userId==='me'?'나':r.userName}</b><small>${r.name} · ${r.location}</small></div><strong>${r.length}cm</strong></div>`).join('')||'<p>아직 순위 기록이 없어요.</p>'}</div>${backButton()}</div>`; }
function toast(message) { document.querySelector('.toast')?.remove(); app.insertAdjacentHTML('beforeend',`<div class="toast">${message}</div>`); setTimeout(()=>document.querySelector('.toast')?.remove(),2400); }
document.addEventListener('DOMContentLoaded',()=>go('camera'));

/* 포인트/랭킹 화면 확장: LocalStorage에 누적합니다. */
function shop(){return `<div class="screen"><button class="icon-btn" onclick="go('camera')">‹</button><h1 class="page-title">포인트 상점</h1><div class="point-balance">보유 포인트 <b>${points()}P</b></div>${[['미끼 교환권','80P'],['해모아 스티커','120P'],['방수 파우치','300P']].map(x=>`<div class="record-card"><div class="thumb">🎁</div><div class="record-meta"><h3>${x[0]}</h3><p>${x[1]}</p></div><button class="secondary" onclick="toast('상점은 프로토타입으로 준비 중입니다.')">교환</button></div>`).join('')}</div>`}
function ranking(){const list=[...records().filter(r=>r.length!=null),...COMMUNITY.filter(r=>r.length!=null).map((r,i)=>({...r,id:'sample'+i,userId:'other'}))].sort((a,b)=>b.length-a.length),shown=state.rankTab==='top'?list.slice(0,3):list;return `<div class="screen"><h1 class="page-title">오늘의 순위</h1><div class="tabs"><button class="${state.rankTab==='top'?'active':''}" onclick="state.rankTab='top';render()">TOP 3</button><button class="${state.rankTab==='all'?'active':''}" onclick="state.rankTab='all';render()">전체 랭킹</button></div><div class="rank-top"><h2>🏆 ${state.rankTab==='top'?'이번 주 TOP 3':'전체 순위'}</h2>${shown.map((r,i)=>`<div class="rank"><b class="rank-num">${state.rankTab==='top'?i+1:list.indexOf(r)+1}</b><div><b>${r.userId==='me'?'나':r.userName}</b><small>${r.name} · ${r.location}</small></div><strong>${r.length}cm</strong></div>`).join('')||'<p>순위 기록이 없어요.</p>'}</div>${backButton()}</div>`}
function storeRecord(){if(!saveGpsRecord())return;grantPoints(1,'해양 생물 기록 저장 보상');setTimeout(()=>go('records'),700)}
