/* 해모아 로컬 프로토타입: API 교체 지점은 analyseImage()에 분리했습니다. */
const app = document.querySelector('#app');
let cameraStream = null;

const LOCATIONS = {
  '광안리': [35.1532, 129.1187], '해운대': [35.1587, 129.1604], '송정': [35.1793, 129.1995],
  '다대포': [35.0488, 128.9651], '영도': [35.0784, 129.0708], '오륙도': [35.0998, 129.1220], '기장': [35.2446, 129.2130]
};
const FISH = [
  { name:'감성돔', category:'어류', classification:'도미과', features:'암초와 방파제 주변에 서식하는 연안 어종입니다.', habitat:'연안 암초·방파제', danger:'주의', edible:'가능', notice:'등지느러미 가시에 찔리지 않도록 주의하세요.', emoji:'🐟' },
  { name:'볼락', category:'어류', classification:'양볼락과', features:'항구와 테트라포드 주변에서 잘 발견되는 야행성 어종입니다.', habitat:'항구·암초 지대', danger:'안전', edible:'가능', notice:'작은 개체는 방류를 권장합니다.', emoji:'🐠' },
  { name:'농어', category:'어류', classification:'농어과', features:'은빛 몸과 강한 입질이 특징인 회유성 어종입니다.', habitat:'하구·연안', danger:'안전', edible:'가능', notice:'지느러미 끝을 조심하세요.', emoji:'🐟' },
  { name:'쥐치', category:'어류', classification:'쥐치과', features:'납작한 몸과 단단한 이빨이 특징입니다.', habitat:'암초·해조류 지대', danger:'안전', edible:'가능', notice:'입 주변을 만질 때 주의하세요.', emoji:'🐡' },
  { name:'복어', category:'어류', classification:'참복과', features:'위협을 받으면 몸을 부풀리는 독성 어종입니다.', habitat:'연안 모래·암초', danger:'위험', edible:'불가', notice:'절대 섭취하거나 맨손으로 다루지 마세요.', emoji:'🐡' },
  { name:'문어', category:'연체동물', classification:'문어과', features:'여덟 개의 팔과 뛰어난 위장 능력을 가졌습니다.', habitat:'바위틈·해저', danger:'주의', edible:'가능', notice:'흡반에 손가락이 끼지 않게 주의하세요.', emoji:'🐙' },
  { name:'꽃게', category:'갑각류', classification:'꽃게과', features:'푸른빛 다리와 넓적한 등딱지가 특징입니다.', habitat:'모래·갯벌', danger:'주의', edible:'가능', notice:'집게에 물리지 않도록 뒤쪽을 잡으세요.', emoji:'🦀' }
];
const COMMUNITY = [
  { location:'광안리', latitude:35.1532, longitude:129.1187, name:'감성돔', category:'어류', length:51.2, userName:'부산 바다낚시' },
  { location:'민락수변공원', latitude:35.1556, longitude:129.1246, name:'농어', category:'어류', length:null, userName:'민락 낚시러' },
  { location:'송정', latitude:35.1801, longitude:129.1998, name:'볼락', category:'어류', length:38.4, userName:'송정 피싱' },
  { location:'영도 태종대', latitude:35.0511, longitude:129.0873, name:'문어', category:'연체동물', length:null, userName:'영도 낚시꾼' },
  { location:'오륙도', latitude:35.0998, longitude:129.1220, name:'쥐치', category:'어류', length:29.6, userName:'오륙도 낚시회' },
  { location:'해운대', latitude:35.1587, longitude:129.1604, name:'꽃게', category:'갑각류', length:null, userName:'해운대 낚시회' },
  { location:'다대포', latitude:35.0488, longitude:128.9651, name:'감성돔', category:'어류', length:42.1, userName:'다대포 바다팀' }
];
let state = { screen:'camera', lengthOn:false, capture:null, fish:null, confidence:0, filter:'전체', mapMode:'mine', selected:null, pendingLength:null, rankTab:'top' };
const points=()=>Number(localStorage.getItem('haemoa-points')||0);
function grantPoints(amount, message){localStorage.setItem('haemoa-points',points()+amount);app.insertAdjacentHTML('beforeend',`<div class="reward-modal"><div><span>🎉</span><h2>+${amount}P</h2><p>${message}</p><button class="primary" onclick="this.closest('.reward-modal').remove()">확인</button></div></div>`)}
const BUSAN_CENTER = [35.1796, 129.0756];
let leafletMap = null, pendingLocation = null;
const records = () => JSON.parse(localStorage.getItem('haemoa-records') || '[]').map(record=>({...record,emoji:record.emoji||getCategoryEmoji(record.category)}));
const saveRecords = value => localStorage.setItem('haemoa-records', JSON.stringify(value));

function stopCamera() { if (cameraStream) { cameraStream.getTracks().forEach(track => track.stop()); cameraStream = null; } }
function go(screen) { stopCamera(); state.screen = screen; state.selected = null; if (screen === 'camera') state.capture = null; render(); if (screen === 'camera') startCamera(); }
function render() { app.innerHTML = ({camera, captureConfirm, analysis, form, records:recordList, map, ranking, shop, locationConfirm}[state.screen] || camera)(); if(state.screen==='map') setTimeout(initRealMap,0); }
function backButton() { return '<button class="back-fab" onclick="go(\'camera\')" aria-label="카메라로 돌아가기">⌾</button>'; }

function camera() { return `<div class="screen camera-screen"><div class="viewfinder"><video id="video" autoplay playsinline muted></video><div class="guide"></div></div><header class="topbar"><div class="brand-logo"><span class="logo-wave">≈</span><span>해모아</span><small>BUSAN SEA</small></div><div class="top-actions"><button class="point-pill" onclick="go('shop')">P ${points()}</button><button class="rank-launch" onclick="go('ranking')">♕ <span>랭킹</span></button></div></header><div class="camera-actions"><button class="tiny-nav" onclick="go('records')" aria-label="나의 기록">▤</button><button class="shutter" onclick="capturePhoto()" aria-label="사진 촬영"></button><button class="tiny-nav map-nav-button" id="mapNavButton" onclick="go('map')" aria-label="바다 생물 지도"><svg class="map-nav-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/></svg></button></div></div>`; }
async function startCamera() { try { cameraStream = await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}, audio:false}); const video = document.querySelector('#video'); if (video) video.srcObject = cameraStream; } catch { toast('카메라 권한이 없으면 촬영 버튼으로 사진을 선택할 수 있어요.'); } }
/* 카메라 프리뷰를 Canvas로 캡처합니다. 파일·갤러리 업로드는 제공하지 않습니다. */
function capturePhoto() { const video = document.querySelector('#video'); if (!video || !video.videoWidth) { toast('카메라 화면이 준비되면 다시 촬영해주세요.'); return; } const limit=1200, ratio=Math.min(1,limit/video.videoWidth), canvas=document.createElement('canvas'); canvas.width=Math.round(video.videoWidth*ratio); canvas.height=Math.round(video.videoHeight*ratio); canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height); state.captureRoi=getAnalysisROI(video,document.querySelector('.guide'),canvas); state.capture=canvas.toDataURL('image/jpeg',.72); stopCamera(); state.screen='captureConfirm'; render(); }
function captureConfirm(){return `<div class="screen"><button class="icon-btn" onclick="go('camera')">‹</button><h1 class="page-title">촬영 사진 확인</h1><p class="sub">사진을 확인한 뒤 분석을 시작하세요.</p><div class="analysis-card"><div class="photo-preview"><img src="${state.capture}" alt="촬영한 해양생물 사진"></div><div class="capture-actions"><button class="secondary" onclick="go('camera')">다시 촬영</button><button class="primary" onclick="beginAnalysis()">분석하기</button></div></div></div>`}
function beginAnalysis() { state.fish=null; state.manualFish=null; state.confidence=0; state.screen='analysis'; render(); setTimeout(showAnalysis,2300); }

/* 실제 Vision API 연결 시 이 함수만 async API 호출로 교체하면 됩니다.
   현재는 업로드한 이미지의 픽셀 특징을 해시해, 같은 사진에는 항상 같은 결과를 제공합니다. */
/* Canvas 픽셀 데이터를 기반으로 평균 RGB·밝기·채도·어두움/밝음 비율을 계산합니다. */
/* ROI 85% + 전체 이미지 15%를 결합하는 Canvas 기반 특징 분석입니다. */
const ROI_WEIGHT=.85,FULL_WEIGHT=.15,DEBUG_ROI=false;
const FEATURE_WEIGHTS={rgb:.30,brightness:.15,saturation:.15,darkRatio:.15,brightRatio:.10,blueRatio:.15};
const ANALYSIS_PROFILES=[[[90,145],[95,150],[95,155],[35,60],[10,35],[20,45],[10,30],[10,30]],[[75,130],[50,100],[45,90],[20,45],[25,55],[35,65],[5,20],[5,20]],[[125,185],[135,190],[140,195],[50,75],[8,30],[10,30],[30,60],[15,35]],[[135,195],[145,200],[145,205],[55,80],[5,25],[5,25],[35,65],[15,35]],[[110,175],[55,115],[40,90],[30,55],[40,75],[20,50],[10,30],[3,15]],[[85,145],[55,110],[50,100],[25,50],[25,60],[30,60],[5,25],[5,20]],[[70,135],[105,165],[120,185],[35,65],[30,65],[15,40],[15,40],[25,55]]];
function calculateAverageRGB(data){let r=0,g=0,b=0,n=data.length/4;for(let i=0;i<data.length;i+=4){r+=data[i];g+=data[i+1];b+=data[i+2]}return{r:r/n,g:g/n,b:b/n}}
function calculateBrightness(rgb){return(.299*rgb.r+.587*rgb.g+.114*rgb.b)/255*100}
function calculateSaturation(data){let t=0,n=data.length/4;for(let i=0;i<data.length;i+=4){const max=Math.max(data[i],data[i+1],data[i+2]),min=Math.min(data[i],data[i+1],data[i+2]);t+=max?(max-min)/max*100:0}return t/n}
function calculateRatio(data,test){let n=0;for(let i=0;i<data.length;i+=4)if(test(data[i],data[i+1],data[i+2]))n++;return n/(data.length/4)*100}
function extractFeatures(imageData){const d=imageData.data,rgb=calculateAverageRGB(d),light=(r,g,b)=>.299*r+.587*g+.114*b;return{rgb,brightness:calculateBrightness(rgb),saturation:calculateSaturation(d),darkRatio:calculateRatio(d,(r,g,b)=>light(r,g,b)<75),brightRatio:calculateRatio(d,(r,g,b)=>light(r,g,b)>185),blueRatio:calculateRatio(d,(r,g,b)=>b>r*1.12&&b>g*1.05)}}
function calculateRangeSimilarity(value,range){const mid=(range[0]+range[1])/2,half=(range[1]-range[0])/2||1;return Math.max(0,1-Math.abs(value-mid)/(half*2))}
function mergeFeatures(roi,full){const mix=(a,b,w=ROI_WEIGHT)=>a*w+b*(1-w);return{rgb:{r:mix(roi.rgb.r,full.rgb.r),g:mix(roi.rgb.g,full.rgb.g),b:mix(roi.rgb.b,full.rgb.b)},brightness:mix(roi.brightness,full.brightness),saturation:mix(roi.saturation,full.saturation),darkRatio:mix(roi.darkRatio,full.darkRatio),brightRatio:mix(roi.brightRatio,full.brightRatio),blueRatio:mix(roi.blueRatio,full.blueRatio,.95)}}
function calculateSpeciesScore(f,p,index){let score=((calculateRangeSimilarity(f.rgb.r,p[0])+calculateRangeSimilarity(f.rgb.g,p[1])+calculateRangeSimilarity(f.rgb.b,p[2]))/3)*FEATURE_WEIGHTS.rgb;['brightness','saturation','darkRatio','brightRatio','blueRatio'].forEach((key,i)=>score+=calculateRangeSimilarity(f[key],p[i+3])*FEATURE_WEIGHTS[key]);if(index===4&&f.rgb.r>f.rgb.g*1.25&&f.rgb.r>f.rgb.b*1.35)score+=.05;if(index===6&&f.rgb.b>f.rgb.r&&f.blueRatio>25)score+=.05;return Math.min(1,score)}
function classifyMarineLife(features){const ranked=FISH.map((fish,i)=>({fish,score:calculateSpeciesScore(features,ANALYSIS_PROFILES[i],i)})).sort((a,b)=>b.score-a.score);return{winner:ranked[0],candidates:ranked.slice(0,3),uncertain:ranked[0].score<.55||ranked[0].score-ranked[1].score<.08}}
/* 화면 guide와 object-fit: cover 영상의 crop을 고려해 Canvas ROI로 변환합니다. */
function getAnalysisROI(video,guide,canvas){if(!guide)return{x:Math.round(canvas.width*.16),y:Math.round(canvas.height*.34),width:Math.round(canvas.width*.68),height:Math.round(canvas.height*.30)};const vr=video.getBoundingClientRect(),gr=guide.getBoundingClientRect(),scale=Math.max(vr.width/video.videoWidth,vr.height/video.videoHeight),cropX=(video.videoWidth*scale-vr.width)/2,cropY=(video.videoHeight*scale-vr.height)/2,convert=(x,y)=>({x:Math.round((x/scale+cropX)*canvas.width/video.videoWidth),y:Math.round((y/scale+cropY)*canvas.height/video.videoHeight)}),a=convert(gr.left-vr.left,gr.top-vr.top),b=convert(gr.right-vr.left,gr.bottom-vr.top);return{x:Math.max(0,a.x),y:Math.max(0,a.y),width:Math.min(canvas.width-a.x,Math.max(1,b.x-a.x)),height:Math.min(canvas.height-a.y,Math.max(1,b.y-a.y))}}
function analyseImage(dataUrl){return new Promise(resolve=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const roi=state.captureRoi||getAnalysisROI(null,null,canvas),roiData=ctx.getImageData(roi.x,roi.y,roi.width,roi.height),roiFeatures=extractFeatures(roiData),fullFeatures=extractFeatures(ctx.getImageData(0,0,canvas.width,canvas.height)),features=mergeFeatures(roiFeatures,fullFeatures);resolve({...classifyMarineLife(features),features,roi})};image.src=dataUrl})}
function analysis(){return `<div class="screen"><button class="icon-btn" onclick="go('captureConfirm')">‹</button><h1 class="page-title">이미지 특징 분석</h1><p class="sub">촬영 사진의 색상·밝기·채도·영역 비율을 계산합니다.</p><div class="analysis-card"><div class="photo-preview"><img src="${state.capture}" alt="촬영한 해양생물 사진"><div id="analyzing" class="analyzing"><div><div class="scan"></div><p id="analysisMessage">이미지를 분석하고 있습니다.</p></div></div></div><div id="analysisInfo" class="hidden"></div></div></div>`}
async function showAnalysis(){const messages=['이미지를 분석하고 있습니다.','색상 특징을 확인하고 있습니다.','밝기와 채도를 분석하고 있습니다.','해양생물 특징을 비교하고 있습니다.'];const msg=document.querySelector('#analysisMessage');messages.forEach((text,i)=>setTimeout(()=>{if(msg)msg.textContent=text},i*520));const result=await analyseImage(state.capture);state.analysisDetails=result.features;state.fish=state.manualFish||{...result.winner.fish,source:'analysis'};state.confidence=Math.round(result.winner.score*100);const mask=document.querySelector('#analyzing'),info=document.querySelector('#analysisInfo');if(!mask||!info)return;mask.classList.add('hidden');info.innerHTML=`<p class="ai-result">이미지 특징 일치도 <b>${state.confidence}%</b></p>${result.uncertain&&!state.manualFish?`<p class="uncertain">정확한 생물 종을 판별하기 어렵습니다.</p><div class="candidate-list"><b>가능성이 높은 생물</b>${result.candidates.map((x,i)=>`<button onclick="selectFish(${FISH.indexOf(x.fish)})">${i+1}. ${x.fish.name} · ${Math.round(x.score*100)}%</button>`).join('')}</div>`:''}${fishInfo(state.fish)}${state.fish.source==='manual'?'<span class="tag">직접 입력</span>':''}<details class="analysis-details"><summary>분석 상세</summary>${analysisDetailsMarkup(result.features)}</details><button class="secondary" onclick="openFishCorrection()">분석 결과 수정</button><button class="primary" onclick="go('form')">이 생물 기록으로 저장</button>`;info.classList.remove('hidden')}
function analysisDetailsMarkup(f){return `<p>분석 방식: 가이드 영역 우선 (85%)</p><p>평균 RGB: R ${Math.round(f.rgb.r)} / G ${Math.round(f.rgb.g)} / B ${Math.round(f.rgb.b)}</p><p>밝기 ${Math.round(f.brightness)}% · 채도 ${Math.round(f.saturation)}%</p><p>어두운 영역 ${Math.round(f.darkRatio)}% · 밝은 영역 ${Math.round(f.brightRatio)}% · 파란 계열 ${Math.round(f.blueRatio)}%</p>`}
function selectFish(index){state.manualFish={...FISH[index],source:'analysis'};state.fish=state.manualFish;render();setTimeout(showAnalysis,0)}
/* 직접 확인한 생물은 이름과 분류를 자유롭게 입력해 분석 결과를 교정합니다. */
const CATEGORY_EMOJI={"어류":"🐟","갑각류":"🦀","연체동물":"🐙","극피동물":"🦔","해조류":"🌿","기타":"🔎"};
function getCategoryEmoji(category){return CATEGORY_EMOJI[category]||'🔎'}
function openFishCorrection(){app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet shop-modal manual-form"><button class="close" onclick="this.closest('.modal').remove()">×</button><h2>분석 결과 수정</h2><p>목록에 없는 해양생물도 직접 등록할 수 있어요.</p><label>해양생물 이름</label><input id="manualName" maxlength="30" placeholder="예: 자리돔, 보라성게, 해파리"><label>어떤 종류인가요?</label><div class="category-picker">${Object.entries(CATEGORY_EMOJI).map(([name,emoji])=>`<button data-category="${name}" onclick="pickManualCategory(this)">${emoji} ${name}</button>`).join('')}</div><p id="manualError" class="manual-error"></p><div class="capture-actions"><button class="secondary" onclick="this.closest('.modal').remove()">취소</button><button class="primary" onclick="applyManualFish()">수정 완료</button></div></div></div>`)}
function pickManualCategory(button){document.querySelectorAll('.category-picker button').forEach(x=>x.classList.remove('active'));button.classList.add('active')}
function applyManualFish(){const name=document.querySelector('#manualName').value.trim(),category=document.querySelector('.category-picker .active')?.dataset.category,error=document.querySelector('#manualError');if(!name){error.textContent='해양생물 이름을 입력해주세요.';return}if(!category){error.textContent='분류를 하나 선택해주세요.';return}state.manualFish={name,category,emoji:getCategoryEmoji(category),classification:'사용자 직접 등록',features:'추가 정보 없음',habitat:'추가 정보 없음',danger:'정보 없음',edible:'추가 정보 없음',notice:'사용자가 직접 등록한 해양생물입니다.',source:'manual'};state.fish=state.manualFish;document.querySelector('.modal').remove();render();setTimeout(showAnalysis,0)}
function fishInfo(f) { return `<div class="fish-head"><div class="fish-icon">${f.emoji}</div><div><h2>${f.name}</h2><p>${f.classification} · ${f.category}</p></div><span class="danger ${dangerClass(f.danger)}">${f.danger}</span></div><dl class="info-grid"><dt>특징</dt><dd>${f.features}</dd><dt>서식 환경</dt><dd>${f.habitat}</dd><dt>식용 가능</dt><dd>${f.edible}</dd><dt>주의사항</dt><dd>${f.notice}</dd></dl>`; }
function dangerClass(value) { return value==='안전'?'safe':value==='주의'?'caution':'risky'; }

function form() { return `<div class="screen"><button class="icon-btn dark-icon" onclick="go('analysis')">‹</button><h1 class="page-title">발견 기록</h1><p class="sub">길이 입력은 선택사항입니다.</p><div class="analysis-card">${fishInfo(state.fish)}<div class="toggle-box"><b>길이 기록</b><button onclick="toggleLength()" class="switch ${state.lengthOn?'on':''}" aria-label="길이 기록 켜기 또는 끄기"><i></i></button></div>${state.lengthOn?'<div class="field"><label>길이를 입력해주세요</label><input id="length" type="number" step="0.1" inputmode="decimal" placeholder="예: 34.5"><small>cm 단위 · 소수점 입력 가능</small></div>':''}<div id="gpsStatus" class="gps-status">기록 저장 전 실제 GPS 위치를 확인합니다.</div><button class="primary" onclick="requestGpsForRecord()">현재 위치 확인하기</button></div>${backButton()}</div>`; }
function toggleLength() { state.lengthOn=!state.lengthOn; render(); }
function requestGpsForRecord() { state.pendingLength=state.lengthOn?Number.parseFloat(document.querySelector('#length')?.value):null; const status=document.querySelector('#gpsStatus'); status.textContent='현재 위치를 확인하고 있습니다...'; if(!navigator.geolocation){ status.textContent='이 브라우저에서는 위치 정보를 사용할 수 없습니다.'; return; } navigator.geolocation.getCurrentPosition(position=>{ pendingLocation={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy}; confirmLocation(); },()=>{ status.textContent='위치 확인에 실패했습니다. localhost 또는 HTTPS에서 위치 권한을 허용해주세요.'; },{enableHighAccuracy:true,timeout:10000,maximumAge:0}); }
function confirmLocation() { state.screen='locationConfirm'; render(); setTimeout(initLocationMap,0); }
function locationConfirm() { return `<div class="screen"><h1 class="page-title">발견 위치 확인</h1><p class="sub">현재 위치가 정확하지 않다면 마커를 움직여 실제 발견 위치를 지정해주세요.</p><div class="gps-status">위치 확인 완료 · 정확도 ±${Math.round(pendingLocation.accuracy)}m</div><div id="locationMap" class="location-map"></div><button class="primary" onclick="storeRecord()">이 위치로 기록 저장</button></div>`; }
function initLocationMap() { const map=L.map('locationMap').setView([pendingLocation.latitude,pendingLocation.longitude],16); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map); const marker=L.marker([pendingLocation.latitude,pendingLocation.longitude],{draggable:true}).addTo(map); marker.on('dragend',()=>{const p=marker.getLatLng();pendingLocation.latitude=p.lat;pendingLocation.longitude=p.lng;}); }
function saveGpsRecord() { if(!pendingLocation || !Number.isFinite(pendingLocation.latitude) || !Number.isFinite(pendingLocation.longitude)){ toast('위치 정보가 없어 저장할 수 없습니다. 위치를 다시 확인해주세요.'); return false; } if(!state.fish){toast('생물 분석 결과가 없어 저장할 수 없습니다.');return false;} const raw=state.pendingLength, now=new Date(); const r={id:Date.now(),userId:'me',userName:'나',...state.fish,length:Number.isFinite(raw)?raw:null,location:pendingLocation.address||`${pendingLocation.latitude.toFixed(6)}, ${pendingLocation.longitude.toFixed(6)}`,latitude:pendingLocation.latitude,longitude:pendingLocation.longitude,accuracy:pendingLocation.accuracy,date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),image:state.capture}; try{saveRecords([r,...records()]);return true;}catch(error){toast('저장 공간이 부족합니다. 브라우저 사이트 데이터를 정리한 뒤 다시 시도해주세요.');console.error('해모아 기록 저장 실패:',error);return false;} }

function filters() { return `<div class="filters">${['전체','어류','갑각류','연체동물','극피동물','해조류','기타'].map(x=>`<button class="filter ${state.filter===x?'active':''}" onclick="setFilter('${x}')">${x}</button>`).join('')}</div>`; }
function setFilter(filter) { state.filter=filter; render(); }
function applyFilter(list) { return state.filter==='전체'?list:list.filter(x=>x.category===state.filter); }
function recordCard(r) { return `<button class="record-card" onclick="detail(${r.id})"><div class="thumb">${r.image?`<img src="${r.image}" alt="${r.name}">`:r.emoji}</div><div class="record-meta"><h3>${r.name} ${r.length!=null?`<span class="tag">${r.length}cm</span>`:''}</h3><p>${r.date.replaceAll('-','.')} · ${r.time}</p><p>⌖ ${r.location}${r.length==null?' · 길이 미기록':''}</p></div><span>›</span></button>`; }
function recordList() { const list=applyFilter(records()); return `<div class="screen"><h1 class="page-title">나의 기록</h1><p class="sub">발견한 순간을 시간순으로 모아보세요.</p>${filters()}<div class="record-list">${list.length?list.map(recordCard).join(''):'<div class="empty">아직 저장한 기록이 없어요.<br>카메라로 첫 발견을 남겨보세요.</div>'}</div>${backButton()}</div>`; }
function detail(id) { const r=records().find(x=>x.id===id); if(!r)return; app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet"><button class="close" onclick="this.closest('.modal').remove()">×</button><div class="photo-preview">${r.image?`<img src="${r.image}" alt="${r.name}">`:''}</div>${fishInfo(r)}<dl class="info-grid"><dt>발견 일시</dt><dd>${r.date} ${r.time}</dd><dt>발견 위치</dt><dd>${r.location}</dd><dt>길이</dt><dd>${r.length!=null?r.length+' cm':'길이 미기록'}</dd></dl></div></div>`); }

function map() { const isMine=state.mapMode==='mine'; return `<div class="screen map-screen"><h1 class="page-title">바다 생물 지도</h1><div class="tabs"><button class="${isMine?'active':''}" onclick="setMapMode('mine')">나의 지도</button><button class="${!isMine?'active':''}" onclick="setMapMode('all')">모두의 지도</button></div>${filters()}<div id="leafletMap" class="leaflet-map" aria-label="실제 부산 지도"></div><div id="mapCard"></div>${backButton()}</div>`; }
function setMapMode(mode) { state.mapMode=mode; state.selected=null; render(); setTimeout(initRealMap,0); }
function initRealMap() { const el=document.querySelector('#leafletMap'); if(!el||!window.L)return; if(leafletMap)leafletMap.remove(); leafletMap=L.map(el).setView(BUSAN_CENTER,11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(leafletMap); const source=state.mapMode==='mine'?records().filter(r=>Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)):COMMUNITY; const list=applyFilter(source); const group=state.mapMode==='all'&&L.markerClusterGroup?L.markerClusterGroup():L.layerGroup(); list.forEach(record=>{const marker=L.marker([record.latitude,record.longitude],{icon:L.divIcon({className:'record-pin',iconSize:[14,14]})}); marker.on('click',()=>showMapCard(record)); group.addLayer(marker);}); group.addTo(leafletMap); if(list.length)leafletMap.fitBounds(group.getBounds(),{padding:[25,25],maxZoom:14}); }
function showMapCard(r) { const card=document.querySelector('#mapCard'); card.innerHTML=`<div class="map-card">${r.image?`<img src="${r.image}" alt="${r.name}">`:''}<b>${r.name}</b>${r.length!=null?' · '+r.length+'cm':''}<br><small>${r.date||'샘플 기록'} ${r.time||''}<br>${r.location}</small></div>`; }

function toast(message) { document.querySelector('.toast')?.remove(); app.insertAdjacentHTML('beforeend',`<div class="toast">${message}</div>`); setTimeout(()=>document.querySelector('.toast')?.remove(),2400); }
document.addEventListener('DOMContentLoaded',()=>go('camera'));

/* 포인트/랭킹 화면 확장: LocalStorage에 누적합니다. */
/* 주간 랭킹: 월요일 00:00부터 일요일 23:59:59까지의 기록만 계산합니다. */
const WEEKLY_REWARDS={1:300,2:200,3:100};
const weekKey=date=>{const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return `${d.getUTCFullYear()}-W${String(Math.ceil((((d-y)/86400000)+1)/7)).padStart(2,'0')}`};
function getCurrentWeek(date=new Date()){return weekKey(date)}
function getWeekDateRange(date=new Date()){const d=new Date(date);const day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);const start=new Date(d),end=new Date(d);end.setDate(end.getDate()+6);end.setHours(23,59,59,999);return{start,end}}
function weeklyDateLabel(){const {start,end}=getWeekDateRange();const f=d=>`${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`;return `${f(start)} ~ ${f(end)}`}
function getWeeklyRanking(date=new Date()){const {start,end}=getWeekDateRange(date),from=start.toISOString().slice(0,10),to=end.toISOString().slice(0,10);const all=[...records(),...COMMUNITY.map((r,i)=>({...r,id:`sample-${i}`,userId:'community-'+i,date:r.date||from,time:r.time||'12:00'}))];const best=new Map();all.filter(r=>r.length!=null&&r.date>=from&&r.date<=to).forEach(r=>{const old=best.get(r.userId);if(!old||r.length>old.length)best.set(r.userId,r)});return [...best.values()].sort((a,b)=>b.length-a.length)}
function settledWeeks(){return JSON.parse(localStorage.getItem('haemoa-settled-weeks')||'[]')}
function weeklyHistory(){return JSON.parse(localStorage.getItem('haemoa-weekly-history')||'[]')}
function saveWeeklyHistory(item){localStorage.setItem('haemoa-weekly-history',JSON.stringify([item,...weeklyHistory()]))}
function showRewardNotification(reward,rank){app.insertAdjacentHTML('beforeend',`<div class="reward-modal"><div><span>🎉</span><h2>지난 주 랭킹 보상</h2><p>지난 주 전체 ${rank}위 달성!</p><b>+${reward}P</b><button class="primary" onclick="this.closest('.reward-modal').remove()">확인</button></div></div>`)}
function giveRankingRewards(winners){const mine=winners.find(w=>w.userId==='me');if(mine){localStorage.setItem('haemoa-points',points()+mine.reward);setTimeout(()=>showRewardNotification(mine.reward,mine.rank),200)}}
function settlePreviousWeek(today=new Date()){const previous=new Date(today);previous.setDate(previous.getDate()-7);const id=getCurrentWeek(previous);if(settledWeeks().includes(id))return;const ranking=getWeeklyRanking(previous).slice(0,3).map((r,i)=>({rank:i+1,userId:r.userId,userName:r.userId==='me'?'나':r.userName,reward:WEEKLY_REWARDS[i+1],name:r.name,length:r.length}));saveWeeklyHistory({weekId:id,startDate:getWeekDateRange(previous).start.toISOString().slice(0,10),endDate:getWeekDateRange(previous).end.toISOString().slice(0,10),settledAt:new Date().toISOString(),winners:ranking});localStorage.setItem('haemoa-settled-weeks',JSON.stringify([...settledWeeks(),id]));localStorage.setItem('haemoa-last-settled-week',id);giveRankingRewards(ranking)}
function checkWeeklySettlement(){const current=getCurrentWeek(),last=localStorage.getItem('haemoa-last-seen-week');if(last&&last!==current)settlePreviousWeek();localStorage.setItem('haemoa-last-seen-week',current)}
function ranking(){checkWeeklySettlement();const list=getWeeklyRanking(),shown=state.rankTab==='top'?list.slice(0,3):list;const {end}=getWeekDateRange(),next=new Date(end);next.setDate(next.getDate()+1);next.setHours(0,0,0,0);const days=Math.max(0,Math.ceil((next-new Date())/86400000));return `<div class="screen"><h1 class="page-title">🏆 이번 주 랭킹</h1><p class="sub">${weeklyDateLabel()} · 매주 월요일 00:00 초기화</p><div class="point-balance">나의 누적 포인트 <b>${points()}P</b><small>다음 랭킹 초기화까지 D-${days}</small></div><div class="tabs"><button class="${state.rankTab==='top'?'active':''}" onclick="state.rankTab='top';render()">TOP 3</button><button class="${state.rankTab==='all'?'active':''}" onclick="state.rankTab='all';render()">전체 랭킹</button></div><div class="rank-top"><h2>${state.rankTab==='top'?'이번 주 TOP 3':'이번 주 전체 순위'}</h2>${shown.map((r,i)=>{const rank=state.rankTab==='top'?i+1:list.indexOf(r)+1;return `<div class="rank"><b class="rank-num">${rank}</b><div><b>${r.userId==='me'?'나':r.userName}</b><small>${r.name} · ${r.location}</small></div><strong>${r.length}cm ${rank<=3?`<em>+${WEEKLY_REWARDS[rank]}P</em>`:''}</strong></div>`}).join('')||'<p>이번 주 길이 기록이 아직 없어요.</p>'}</div>${backButton()}</div>`}
window.haemoaWeeklySettlementTest=()=>{settlePreviousWeek(new Date(Date.now()+7*86400000));render()};
document.addEventListener('DOMContentLoaded',checkWeeklySettlement);

/* 포인트 상점: 상품은 이 배열만 수정하면 추가·가격 변경이 가능합니다. */
const shopItems=[
 {id:'sticker',name:'해모아 방수 스티커팩',category:'해모아 굿즈',price:200,icon:'🏷️',description:'부산 바다와 감성돔·볼락·문어·꽃게 그래픽을 담은 방수 스티커 세트.',badge:'HAEMOA ORIGINAL'},
 {id:'hook',name:'낚시 바늘 세트',category:'낚시용품',price:300,icon:'🪝',description:'다양한 크기의 기본 낚시 바늘 세트.'},
 {id:'notebook',name:'해모아 물고기 노트',category:'해모아 굿즈',price:400,icon:'📒',description:'감성돔·볼락·문어 페이지로 구성된 해양생물 기록 노트.',badge:'HAEMOA ORIGINAL'},
 {id:'pliers',name:'낚시 플라이어',category:'낚시용품',price:500,icon:'🔧',description:'바늘 제거와 낚시 채비 정리에 쓰는 플라이어.'},
 {id:'towel',name:'해모아 낚시 타월',category:'해모아 굿즈',price:600,icon:'🧻',description:'부산 바다 그래픽을 적용한 마이크로화이버 타월.',badge:'HAEMOA ORIGINAL'},
 {id:'mat',name:'해모아 물고기 계측매트',category:'해모아 굿즈',price:700,icon:'📏',description:'물고기 길이를 직접 기록하는 해모아 계측매트.',badge:'랭킹 도전 추천'},
 {id:'cap',name:'해모아 낚시 모자',category:'해모아 굿즈',price:800,icon:'🧢',description:'야외 낚시에 쓸 수 있는 해모아 로고 캡.',badge:'HAEMOA ORIGINAL'},
 {id:'pouch',name:'해모아 방수 파우치',category:'해모아 굿즈',price:1000,icon:'👜',description:'낚시 중 소형 장비를 보관하는 방수 파우치.',badge:'HAEMOA ORIGINAL'},
 {id:'tacklebox',name:'소형 태클박스',category:'낚시용품',price:1200,icon:'🧰',description:'바늘·봉돌·루어를 보관하는 소형 태클박스.'},
 {id:'lure',name:'루어/채비 키트',category:'낚시용품',price:1500,icon:'🎣',description:'루어낚시와 찌낚시에 사용할 수 있는 기본 키트.'},
 {id:'bag',name:'해모아 낚시 가방',category:'해모아 굿즈',price:2000,icon:'🎒',description:'낚시 장비를 넉넉히 담는 프리미엄 해모아 가방.',badge:'PREMIUM'},
 {id:'lifejacket',name:'낚시용 구명조끼',category:'안전용품',price:2500,icon:'🦺',description:'안전한 낚시를 위한 필수 장비.'},
 {id:'reel',name:'낚시 릴',category:'낚시용품',price:3500,icon:'⚙️',description:'포인트를 오래 모은 사용자를 위한 프리미엄 릴.'},
 {id:'rod',name:'낚싯대',category:'낚시용품',price:5000,icon:'🎣',description:'상점의 최고 보상 상품인 낚싯대.',badge:'BEST REWARD'}
];
let shopCategory='전체',shopBusy=false;
const exchangeHistory=()=>JSON.parse(localStorage.getItem('haemoa-exchange-history')||'[]');
function shop(){const items=shopCategory==='전체'?shopItems:shopItems.filter(x=>x.category===shopCategory);return `<div class="screen shop-screen"><button class="icon-btn" onclick="go('camera')">‹</button><h1 class="page-title">포인트 상점</h1><div class="point-balance">보유 포인트 <b>${points().toLocaleString()}P</b><small>주간 랭킹 보상으로 모은 포인트</small></div><div class="shop-head"><b>리워드 스토어</b><button class="secondary" onclick="showExchangeHistory()">교환 내역</button></div><div class="filters">${['전체','해모아 굿즈','낚시용품','안전용품'].map(c=>`<button class="filter ${shopCategory===c?'active':''}" onclick="shopCategory='${c}';render()">${c}</button>`).join('')}</div><div class="shop-grid">${items.map(shopCard).join('')}</div></div>`}
function shopCard(item){const lack=Math.max(0,item.price-points());return `<article class="shop-card" onclick="showShopDetail('${item.id}')"><div class="product-art">${item.badge?`<span>${item.badge}</span>`:''}<b>${item.icon}</b></div><small>${item.category}</small><h3>${item.name}</h3><p>${item.description}</p><strong>${item.price.toLocaleString()}P</strong><button class="${lack?'shop-disabled':'primary'}" ${lack?'disabled':''} onclick="event.stopPropagation();${lack?'':'showExchangeConfirm(\''+item.id+'\')'}">${lack?`${lack.toLocaleString()}P 더 필요해요`:'교환하기'}</button></article>`}
function showShopDetail(id){const item=shopItems.find(x=>x.id===id),lack=Math.max(0,item.price-points());app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet shop-modal"><button class="close" onclick="this.closest('.modal').remove()">×</button><div class="product-art large">${item.icon}</div><p class="tag">${item.category}</p><h2>${item.name}</h2><p>${item.description}</p><dl class="info-grid"><dt>상품 가격</dt><dd>${item.price.toLocaleString()}P</dd><dt>보유 포인트</dt><dd>${points().toLocaleString()}P</dd><dt>교환 후</dt><dd>${Math.max(0,points()-item.price).toLocaleString()}P</dd></dl><button class="${lack?'shop-disabled':'primary'}" ${lack?'disabled':''} onclick="this.closest('.modal').remove();showExchangeConfirm('${id}')">${lack?`${lack.toLocaleString()}P 더 필요해요`:'교환하기'}</button></div></div>`)}
function showExchangeConfirm(id){const item=shopItems.find(x=>x.id===id);if(points()<item.price){toast('포인트가 부족합니다.');return}app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet shop-modal"><button class="close" onclick="this.closest('.modal').remove()">×</button><h2>상품을 교환할까요?</h2><p><b>${item.name}</b></p><p>${item.price.toLocaleString()}P가 사용됩니다.</p><div class="point-balance">현재 ${points().toLocaleString()}P <b>→ ${(points()-item.price).toLocaleString()}P</b></div><button class="primary" onclick="completeExchange('${id}',this)">교환하기</button></div></div>`)}
function completeExchange(id,button){if(shopBusy)return;const item=shopItems.find(x=>x.id===id);if(points()<item.price){toast('포인트가 부족합니다.');return}shopBusy=true;button.disabled=true;localStorage.setItem('haemoa-points',points()-item.price);localStorage.setItem('haemoa-exchange-history',JSON.stringify([{id:Date.now(),itemId:item.id,name:item.name,price:item.price,date:new Date().toISOString().slice(0,10),status:'교환 완료'},...exchangeHistory()]));button.closest('.modal').remove();shopBusy=false;app.insertAdjacentHTML('beforeend',`<div class="reward-modal"><div><span>🎉</span><h2>교환 완료!</h2><p>${item.name}을 교환했습니다.</p><b>${item.price.toLocaleString()}P 사용 · 남은 포인트 ${points().toLocaleString()}P</b><button class="primary" onclick="this.closest('.reward-modal').remove();render()">확인</button></div></div>`)}
function showExchangeHistory(){const list=exchangeHistory();app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-sheet shop-modal"><button class="close" onclick="this.closest('.modal').remove()">×</button><h2>교환 내역</h2>${list.length?list.map(x=>`<div class="history-row"><div><b>${x.name}</b><small>${x.date} · ${x.status}</small></div><strong>${x.price.toLocaleString()}P</strong></div>`).join(''):'<p class="empty">아직 교환한 상품이 없어요.</p>'}</div></div>`)}
function storeRecord(){if(!saveGpsRecord())return;grantPoints(1,'해양 생물 기록 저장 보상');setTimeout(()=>go('records'),700)}
